export const ADMIN_HTML = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Tailscale 管理</title>
<style>body{font-family:system-ui,-apple-system,"Segoe UI",sans-serif;margin:0;background:#f6f7f9;color:#202124}main{max-width:1320px;margin:32px auto;padding:0 20px}h1{font-size:24px;margin:0 0 8px}.muted{color:#6b7280}.toolbar{display:flex;gap:8px;margin:24px 0 14px}.toolbar input{flex:1;padding:10px 12px;border:1px solid #d1d5db;border-radius:7px;font-size:15px}button,select{padding:8px 11px;border:1px solid #c7ccd4;border-radius:6px;background:#fff;cursor:pointer}button.primary{background:#2563eb;color:#fff;border-color:#2563eb}table{width:100%;border-collapse:collapse;background:#fff;border:1px solid #e5e7eb}th,td{text-align:left;padding:12px;border-bottom:1px solid #eef0f3;vertical-align:top}th{font-size:13px;color:#6b7280;background:#fafafa}.device,.key-detail{font-size:13px;margin:3px 0}.status{display:inline-block;padding:2px 7px;border-radius:99px;background:#e5e7eb;font-size:12px}.online{background:#dcfce7;color:#166534}.revoked{background:#fee2e2;color:#991b1b}.used{background:#dbeafe;color:#1d4ed8}.message{margin:12px 0;color:#166534}.error{color:#b91c1c}</style></head>
<body><main><h1>Tailscale 用户管理</h1><div class="muted">按邮箱或姓名搜索；权限变化会同步到已登记设备，未来新设备会使用新 Tag。</div>
<div class="toolbar"><input id="search" placeholder="搜索邮箱或姓名"><button class="primary" id="reload">刷新</button></div><div id="message" class="message"></div>
<table><thead><tr><th>用户</th><th>权限</th><th>最新密钥</th><th>Tailscale 设备</th><th>操作</th></tr></thead><tbody id="users"></tbody></table></main>
<script>
var message=document.getElementById('message');
function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function setMessage(value,error){message.textContent=value||'';message.className=error?'message error':'message'}
async function api(path,options){var response=await fetch(path,Object.assign({headers:{'content-type':'application/json'}},options||{}));var body=await response.json().catch(function(){return {}});if(!response.ok)throw new Error(body.error||response.statusText);return body}
function formatTime(value){return value?new Date(value*1000).toLocaleString('zh-CN'):'—'}
function renderKey(key){if(!key)return '<span class="muted">尚未签发</span>';var state=(key.revoked?'<span class="status revoked">已撤销</span> ':'')+(key.used?'<span class="status used">已使用</span> ':'');return '<div class="key-detail">'+state+'</div><div class="key-detail">签发：'+esc(formatTime(key.issuedAt))+'</div><div class="key-detail">到期：'+esc(formatTime(key.expiresAt))+'</div><div class="key-detail">'+esc(key.role)+' · '+esc(key.tag)+'</div>'}
function render(data){document.getElementById('users').innerHTML=(data.users||[]).map(function(user){var devices=(user.devices||[]).map(function(device){return '<div class="device"><span class="status '+(device.online?'online':'')+'">'+(device.online?'在线':'离线')+'</span> '+esc(device.hostname||device.nodeId)+' · '+esc(device.tag)+'</div>'}).join('')||'<span class="muted">尚未登记设备</span>';return '<tr><td><strong>'+esc(user.displayName||'未命名')+'</strong><br><span class="muted">'+esc(user.email||user.accessSubject)+'</span></td><td><select data-role="'+esc(user.accessSubject)+'"><option value="user" '+(user.tailscaleRole==='user'?'selected':'')+'>普通用户</option><option value="admin" '+(user.tailscaleRole==='admin'?'selected':'')+'>管理用户</option></select></td><td>'+renderKey(user.latestKey)+'</td><td>'+devices+'</td><td><button data-save="'+esc(encodeURIComponent(user.accessSubject))+'">保存权限</button></td></tr>'}).join('');document.querySelectorAll('[data-save]').forEach(function(button){button.addEventListener('click',async function(){var subject=decodeURIComponent(button.getAttribute('data-save'));var select=document.querySelector('[data-role="'+CSS.escape(subject)+'"]');button.disabled=true;try{await api('/v1/admin/users/'+encodeURIComponent(subject)+'/role',{method:'PATCH',body:JSON.stringify({role:select.value})});setMessage('权限已更新');await load()}catch(error){setMessage(error.message,true)}finally{button.disabled=false}})})}
async function load(){try{var query=document.getElementById('search').value.trim();render(await api('/v1/admin/users'+(query?'?search='+encodeURIComponent(query):'')))}catch(error){setMessage(error.message,true)}}
document.getElementById('reload').addEventListener('click',load);document.getElementById('search').addEventListener('keydown',function(event){if(event.key==='Enter')load()});load();
</script></body></html>`
